apiVersion: v1
kind: Pod
metadata:
  name: qwen-image-edit-api
  labels:
    app: qwen-image-edit
    version: v1
spec:
  containers:
  - name: qwen-edit-api
    image: us-east4-docker.pkg.dev/genai-aas/test-images/qwen-image:lab3
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    env:
    - name: DIFFUSER_HOST
      value: "0.0.0.0"
    - name: DIFFUSER_PORT
      value: "8000"
    - name: DIFFUSER_DEVICE
      value: "cuda"
    - name: DIFFUSER_TORCH_DTYPE
      value: "bfloat16"
    - name: DIFFUSER_ENABLE_WARMUP
      value: "false"
    resources:
      requests:
        nvidia.com/gpu: 1
        memory: "32Gi"
        cpu: "8"
      limits:
        nvidia.com/gpu: 1
        memory: "32Gi"
        cpu: "8"
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

